route:
    receiver: 'slack'
    routes:
        - match:
            alertname: InstanceDown

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            #username: <user>#
            #channel: <channel>#
            #api_url: <url>#
