remote_write:
- url: https://cloud.weave.works/api/prom/push
  basic_auth:
    #password: <token>#

global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'promswarm'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

